/**:
  ros__parameters:
    family: "Custom48h12" # options: Standard52h13, Standard41h12, 36h11, 25h9, 16h5, Custom48h12, Circle21h7, Circle49h12
    size: 0.3                # default tag size
    max_hamming: 2           # maximum allowed hamming distance

    detector:
      threads: 2
      decimate: 1.0
      blur: 0.0
      refine: true
      sharpening: 0.25
      debug: false

    pose_estimation_method: "pnp" # method for estimating tag pose

    tag:
      ids:
        - 0
        - 10
      frames:
        - "Custom48h12:0"
        - "Custom48h12:10"
      sizes:
        - 0.3
        - 0.06
